
services:

  config-service:
    build: ./config-service
    container_name: config-service
    ports:
      - '8888:8888'

    networks:
      - microservices-net

  eureka-service:
    build: ./eureka-service
    container_name: eureka-service
    ports:
      - '8761:8761'
    depends_on:
      - config-service

    networks:
      - microservices-net

  gateway-service:
    build: ./gateway-service
    container_name: gateway-service
    ports:
      - '8085:8085'
    depends_on:
      - eureka-service
      - config-service

    networks:
      - microservices-net

  user-service:
    build: ./user-service
    container_name: user-service
    ports:
      - '8081:8081'
    depends_on:
      - eureka-service
      - config-service

    networks:
      - microservices-net

  fraud-detection-service:
    build: ./Fraud-Detection-service
    container_name: fraud-detection-service
    ports:
      - '8087:8087'
    depends_on:
      - eureka-service
      - config-service

    networks:
      - microservices-net

  notification-service:
    build: ./notification-service
    container_name: notification-service
    ports:
      - '8099:8099'
    depends_on:
      - eureka-service
      - config-service

    networks:
      - microservices-net

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: pfe_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 0000
    ports:
      - "5432:5432"
    networks:
      - microservices-net

  keycloak:
    image: quay.io/keycloak/keycloak:21.1.2
    container_name: keycloak
    command: start-dev
    ports:
      - "8080:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    networks:
      - microservices-net

  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - microservices-net

  kafka:
    image: confluentinc/cp-kafka:7.6.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - microservices-net




networks:
  microservices-net:
