

spring:
  # Configuration Keycloak pour OAuth2
  security:
    oauth2:
      resource-server:
        jwt:
          jwk-set-uri: ${keycloak-client.server-url}/realms/${keycloak-client.realm}/protocol/openid-connect/certs


  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:4200"
            allowedMethods:
              - PUT
              - GET
              - POST
              - DELETE
            AllowedHeaders:
              - Content-Type
      discovery:
        locator:
          enabled: true

      routes:
        - id: user-service
          uri: http://localhost:8090
          predicates:
              - Path=/users/**
              - Method=GET,POST,PUT,DELETE,OPTIONS


        - id: transaction-service
          uri: http://localhost:8087
          predicates:

            - Path=/userss/**,/accounts/**,/cards/**,/banks/**,/transactions/**,/api/dashboard/**,/claims/**,/exchange/**
            - Method=GET,POST,PUT,DELETE,OPTIONS

# Configuration Eureka
eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

# Configuration du serveur
server:
  port: 8085

# Configuration des logs
logging:
  level:
    org.springframework.cloud.gateway: INFO

# Configuration du monitoring
management:
  endpoints:
    web:
      exposure:
        include: "*"

# Configuration Keycloak (variables externes)
keycloak-client:
  server-url: http://localhost:8080
  realm: spring-micro-main

# Nom de l'application

  application:
    name: gateway-service