

spring:
  # Configuration Keycloak pour OAuth2
  security:
    oauth2:
      resource-server:
        jwt:
#          issuer-uri: http://keycloak:8080/realms/spring-micro-main

            jwk-set-uri: ${KEYCLOAK_URL:http://localhost:8080}/realms/${KEYCLOAK_REALM:spring-micro-main}/protocol/openid-connect/certs



  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: ${FRONTEND_URL:http://localhost:4200}
            allowedMethods:
              - PUT
              - GET
              - POST
              - DELETE
            allowedHeaders:
              - Content-Type
      discovery:
        locator:
          enabled: true

      routes:
        - id: user-service
          uri: ${USER_SERVICE_URL:http://localhost:8090}
          predicates:
              - Path=/users/**
              - Method=GET,POST,PUT,DELETE,OPTIONS


        - id: transaction-service
          uri: ${FRAUD_SERVICE_URL:http://localhost:8087}
          predicates:

            - Path=/userss/**,/accounts/**,/cards/**,/banks/**,/transactions/**,/api/dashboard/**,/claims/**,/exchange/**
            - Method=GET,POST,PUT,DELETE,OPTIONS

# Configuration Eureka
eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}

# Configuration du serveur
server:
  port: 8085

# Configuration des logs
logging:
  level:
    org.springframework.cloud.gateway: INFO

# Configuration du monitoring
management:
  endpoints:
    web:
      exposure:
        include: "*"

# Configuration Keycloak (variables externes)
keycloak-client:
  server-url: ${KEYCLOAK_URL:http://localhost:8080}
  realm: ${KEYCLOAK_REALM:spring-micro-main}

# Nom de l'application

  application:
    name: gateway-service