#########config keycloak############
keycloak-client:
  server-url: http://localhost:8080
  realm:  spring-micro-main

spring:
  security:
    oauth2:
      resource-server:
        jwt:
          jwk-set-uri: ${keycloak-client.server-url}/realms/${keycloak-client.realm}/protocol/openid-connect/certs
#########       ############
eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:4200"
            allowedMethods:
              - PUT
              - GET
              - POST
              - DELETE
            AllowedHeaders:
              - Content-Type
      discovery:
        locator:
          enabled: true
      routes: # Ajoute tes routes ici
        - id: user-service
          uri: http://localhost:8090
          predicates:
            - Path=/users/**


  logging:
    level:
      org.springframework.cloud.gateway: DEBUG

  application:
    name : gateway-service

server:
  port: 8085
management:
  endpoints:
    web:
      exposure:
        include: "*"


