#spring.application.name=kafka-service
server:
  port: 8033
spring:
  kafka:


    consumer:
      group-id: myGrp

     # bootstrap-servers: localhost:9092
     # group-id: myGrp
     # auto-offset-reset: earliest
     # key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      #value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
     # value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
     # properties:
       # spring.json.trusted.packages: '*'
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer


    bootstrap-servers: localhost:9092


