spring:

#  cloud:
##    config:
##      uri: ${CONFIG_SERVER_URL:http://localhost:8888}

  application:
    name: user-service

  config:
    import: configserver:${CONFIG_SERVER_URL:http://localhost:8888}


#server:
#  port: 8090





