spring:
  config:
    import: configserver:http://localhost:8888  # Importer les configurations depuis le serveur de configuration

  application:
    name: transaction-service
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: debezium-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer