server:
  port: 8888

spring:
  application:
    name: config-service
  profiles:

    active: native
  cloud:
    config:
      enabled : false
      server:
        native:
          search-locations:  classpath:/configurations
         # search-locations: file:///C:/Users/Lenovo/Desktop/stagePfe/BackOffice_PFE/pfaMicros/config-service/src/main/resources/configurations


