name: Build and Push Docker Image

on:
  push:
    branches:
      - production

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Set up JDK for building the project
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # Grant execute permission to Maven Wrapper

      # Clean up old JAR files (optional step)
      # Clean up old JAR files (optional step)


      # Build the  Test unitaire
      - name: Build the  Test unitaire
        run: mvn  test


        # Build the Spring Boot application
      - name: Build Spring Boot JAR
        run:  mvn clean  install -DskipTests

      #  Analyse SonarQube
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@v1
        with:
          organization: imenNfaiedh
          projectKey: imenNfaiedh_BackOffice_PFE_WEVIOO
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}



      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

        # Étape 3 : Construire tous les services définis dans docker-compose.yml
      - name: Build Docker Compose services
        run: docker compose build

      # Push Docker image to Docker Hub
      - name: Tag and Push Docker Images
        run: |
          docker tag backoffice_pfe_wevioo-config-service:latest ${{ secrets.DOCKER_USERNAME }}/config-service:latest
          docker tag backoffice_pfe_wevioo-eureka-service:latest ${{ secrets.DOCKER_USERNAME }}/eureka-service:latest
          docker tag backoffice_pfe_wevioo-gateway-service:latest ${{ secrets.DOCKER_USERNAME }}/gateway-service:latest
          docker tag backoffice_pfe_wevioo-fraud-detection-service:latest ${{ secrets.DOCKER_USERNAME }}/fraud-detection-service:latest
          docker tag backoffice_pfe_wevioo-user-service:latest ${{ secrets.DOCKER_USERNAME }}/user-service:latest
          docker tag backoffice_pfe_wevioo-notification-service:latest ${{ secrets.DOCKER_USERNAME }}/notification-service:latest
                    
         
          docker push ${{ secrets.DOCKER_USERNAME }}/config-service:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/eureka-service:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/gateway-service:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/fraud-detection-service:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/user-service:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/notification-service:latest
          
          
      
      
      
      
      
      
      

    
