name: Build, Analyze with SonarCloud, and Push Docker Image

on:
  push:
    branches:
      - production

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Récupérer le code source
        uses: actions/checkout@v3

      - name: ☕ Installer JDK Temurin 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # Run unit tests (et compile une première fois)
      - name: 🧪 Lancer les tests unitaires
        run: mvn test

      # Compile seulement (nécessaire pour SonarCloud)
      - name: 🛠️ Compiler les classes Java
        run: mvn compile

      # Analyse SonarCloud (doit être après la compilation)
      - name: 🔍 Analyse SonarCloud
        run: mvn sonar:sonar -Dsonar.projectKey=pfeFraud -Dsonar.organization=imennfaiedh -Dsonar.host.url=https://sonarcloud.io -Dsonar.language=java -Dsonar.sources=config-service/src/main/java -Dsonar.java.binaries=config-service/target/classes
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}


      # Build Spring Boot JAR (skip tests, déjà exécutés)
      - name: 📦 Construire le JAR Spring Boot
        run: mvn clean install -DskipTests

      # Docker Hub login
      - name: 🔐 Connexion à Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build all Docker Compose services
      - name: 🏗️ Construire les services Docker Compose
        run: docker compose build

      # Tag and Push Docker Images
      - name: 🏷️ Taguer et pousser les images Docker

        run: |
          docker tag backoffice_pfe_wevioo-config-service:latest ${{ secrets.DOCKER_USERNAME }}/config-service:latest
          docker tag backoffice_pfe_wevioo-eureka-service:latest ${{ secrets.DOCKER_USERNAME }}/eureka-service:latest
          docker tag backoffice_pfe_wevioo-gateway-service:latest ${{ secrets.DOCKER_USERNAME }}/gateway-service:latest
          docker tag backoffice_pfe_wevioo-fraud-detection-service:latest ${{ secrets.DOCKER_USERNAME }}/fraud-detection-service:latest
          docker tag backoffice_pfe_wevioo-user-service:latest ${{ secrets.DOCKER_USERNAME }}/user-service:latest
          docker tag backoffice_pfe_wevioo-notification-service:latest ${{ secrets.DOCKER_USERNAME }}/notification-service:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/config-service:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/eureka-service:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/gateway-service:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/fraud-detection-service:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/user-service:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/notification-service:latest
