name: Build, Analyze with SonarCloud, and Push Docker Image

on:
  push:
    branches:
      - production

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # Run unit tests (et compile une première fois)
      - name: Run Unit Tests
        run: mvn test

      # Compile seulement (nécessaire pour SonarCloud)
      - name: Compile Java (generate .class files)
        run: mvn compile

      # Analyse SonarCloud (doit être après la compilation)
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        with:
          organization: imennfaiedh  # ⚠️ attention à bien utiliser le vrai key
          projectKey: pfeFraud       # ⚠️ idem, vérifie que ce projet existe
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: 'https://sonarcloud.io'

      # Build Spring Boot JAR (skip tests, déjà exécutés)
      - name: Build Spring Boot JAR
        run: mvn clean install -DskipTests

      # Docker Hub login
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build all Docker Compose services
      - name: Build Docker Compose services
        run: docker compose build

      # Tag and Push Docker Images
      - name: Tag and Push Docker Images
        run: |
          docker tag backoffice_pfe_wevioo-config-service:latest ${{ secrets.DOCKER_USERNAME }}/config-service:latest
          docker tag backoffice_pfe_wevioo-eureka-service:latest ${{ secrets.DOCKER_USERNAME }}/eureka-service:latest
          docker tag backoffice_pfe_wevioo-gateway-service:latest ${{ secrets.DOCKER_USERNAME }}/gateway-service:latest
          docker tag backoffice_pfe_wevioo-fraud-detection-service:latest ${{ secrets.DOCKER_USERNAME }}/fraud-detection-service:latest
          docker tag backoffice_pfe_wevioo-user-service:latest ${{ secrets.DOCKER_USERNAME }}/user-service:latest
          docker tag backoffice_pfe_wevioo-notification-service:latest ${{ secrets.DOCKER_USERNAME }}/notification-service:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/config-service:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/eureka-service:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/gateway-service:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/fraud-detection-service:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/user-service:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/notification-service:latest
